### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by agarrharr** [niieani/chunk-splitting-plugin#18]

**Comment by niieani** [comment]
It's in the repo, MIT: 

https://github.com/niieani/chunk-splitting-plugin/blob/master/LICENSE

**Comment by agarrharr** [comment]
Oh ok, thanks. I missed that. And apparently Github didn't pick up on it either.

**Comment by niieani** [comment]
@agarrharr Where does GitHub display the license?

**Comment by agarrharr** [comment]
Normally, it would be at the top right, next to the number of contributers. See the bottom right of this image:

![1](https://user-images.githubusercontent.com/3266363/29139569-9e60fcbc-7d04-11e7-99ab-837d2de982d0.png)

**Comment by agarrharr** [comment]
But it probably only works if the full text of the license is in the license file.

**Comment by niieani** [comment]
Ah, I see. Thanks.
