### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by athomann** [niieani/chunk-splitting-plugin#20]
I'm splitting my app into multiple entries, client & vendor.  I'm receiving `client.2749b91fd530efe295ca.js:1 Uncaught ReferenceError: webpackJsonp is not defined` when adding ChunkSplittingPlugin to webpack.

**Comment by niieani** [comment]
Hi @athomann. The problem is that your chunks are not getting executed in the proper order. Do you use HtmlWebpackPlugin or something else?

See: https://github.com/niieani/chunk-splitting-plugin#the-correct-order-of-loading-chunks

**Comment by flakey-bit** [comment]
This is affecting me too. 

Plugins section of my config is as follows:

```
    plugins: [
        new HtmlWebpackPlugin({
            inject: 'head',
            title: '{{pageTitle}}',
            template: './app/index.html',
            chunks: ['vendor', 'app']
        }),
        new HtmlWebpackPlugin({
          filename: 'ErrorPage.html',
          template: './app/ErrorPage.html',
          chunks: []
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: "vendor",
            filename: "vendor-[chunkhash].js",
            minChunks: Infinity
        }),
        new ChunkSplittingPlugin({
        maxModulesPerChunk: 10,
        maxModulesPerEntry: 1
        })
    ],

```

If I comment-out the chunks property on the HtmlWebpackPlugin entries I don't see this problem. The issue is that only app-5201fd41d86b0240b567.js is getting injected, rather than app-part-01-6f62844e4bef209881a9.js, app-part-02-7675c319540de97e1dfc.js, ...  app-5201fd41d86b0240b567.js

**Comment by niieani** [comment]
@flakey-bit try using `excludeChunks` instead of chunks property in the configuration of HtmlWebpackPlugin. Or use the `html-webpack-plugin-alter-chunks` plugin hook to filter the chunks yourself.
